version: '3'

services:
  mautic4:
    image: nexus.gnet.tn:8443/gmarket/tmautic:v4-apache
    container_name: mautic4
    restart: always
    ports:
      - "8084:80"
    environment:
      MAUTIC_URL: http://gmarket.gnet.tn/client4
      MAUTIC_DB_HOST: db4
      MAUTIC_DB_USER: mautic4
      MAUTIC_DB_PASSWORD: mautic1_password
      MAUTIC_DB_NAME: mautic4_db
      MAUTIC_RUN_CRON_JOBS: 'false'
    volumes:
      - mautic4_data:/var/www/html

  mautic5:
    image: nexus.gnet.tn:8443/gmarket/tmautic:v4-apache
    container_name: mautic5
    restart: always
    ports:
      - "8085:80"
    environment:
      MAUTIC_URL: http://gmarket.gnet.tn/client5
      MAUTIC_DB_HOST: db5
      MAUTIC_DB_USER: mautic5
      MAUTIC_DB_PASSWORD: mautic5_password
      MAUTIC_DB_NAME: mautic5_db
      MAUTIC_RUN_CRON_JOBS: 'false'
    volumes:
      - mautic5_data:/var/www/html

  db4:
    image: mariadb:10.6
    container_name: mautic_db4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mautic4_db
      MYSQL_USER: mautic4
      MYSQL_PASSWORD: mautic4_password
    ports:
      - "3307:3306"  # Change the host port to a different port, e.g., "3307:3306"
    volumes:
      - db4_data:/var/lib/mysql

  db5:
    image: mariadb:10.6
    container_name: mautic_db5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mautic5_db
      MYSQL_USER: mautic5
      MYSQL_PASSWORD: mautic5_password
    ports:
      - "3309:3306"  # Use a different host port, e.g., "3307:3306"
    volumes:
      - db5_data:/var/lib/mysql

 



volumes:
  mautic4_data:
  mautic5_data:
 # mautic3_data:
  db4_data:
  db5_data:
#  db3_data:                            

















































































































































































































































































































































































































































































































































