apiVersion: v1
kind: PersistentVolume
metadata:
  name: mautic-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: ~/gmarket

